### ISSUE TITLE
Run CLN in Docker $@500000

### ISSUE THREAD

**Issue by Evanfeenstra** [stakwork/sphinx-stack#42]
make a docker-compose setup with bitcoind and CLN running together.

I started one from scratch and failed :(  But here is my progress:

docker-compose.yml
```
version: "3"

services:

  bitcoind:
    image: lncm/bitcoind:v0.21.1
    restart: on-failure
    container_name: bitcoind
    volumes:
      - ./bitcoind:/data/.bitcoin
    ports:
      - 18443:18443
      - 8333:8333
      - 28332:28332
      - 28333:28333

  alice-cln:
    image: elementsproject/lightningd
    restart: on-failure
    container_name: alice-cln
    links:
      - bitcoind
    volumes:
      - ./lightning/regtest:/root/.lightning/regtest
      - ./bitcoind:/root/.bitcoin
    ports:
      - 10019:10019
    command: |
      --network=regtest
```

lightning/config
```
bitcoin-rpcuser=theuser
bitcoin-rpcpassword=thepass
bitcoin-rpcconnect=bitcoind
bitcoin-rpcport=18443
grpc-port=10019
```

bitcoind/bitcoin.conf:
```
regtest=1
fallbackfee=0.0002
rpcuser=theuser
rpcpassword=thepass
zmqpubhashblock=tcp://0.0.0.0:28332
zmqpubhashtx=tcp://0.0.0.0:28333

[regtest]
txindex=1
server=1
rpcport=18443
rpcbind=bitcoind
rpcbind=127.0.0.1
rpcallowip=0.0.0.0/0
```
