### ISSUE TITLE
CLN-based proxy full test suite

### ISSUE THREAD

**Issue by Evanfeenstra** [stakwork/sphinx-stack#60]
test suite like this one: https://github.com/stakwork/sphinx-stack/blob/master/alts/proxy.yml

Except with CLN instead.

Instead of LND, using the image and configs found here https://github.com/stakwork/sphinx-swarm/blob/master/src/images/cln.rs (no external signer)

And instead of lndsetup, it will need a clnsetup to create the initial channels

**Comment by Evanfeenstra** [comment]
The CLN config is something like this:

```
cln1:
    image: sphinxlightning/cln-sphinx:0.1.1
    container_name: dave-cln.sphinx
    command:
      - --bitcoin-rpcconnect=bitcoind.sphinx
      - --bitcoin-rpcport=18443
      - --bitcoin-rpcuser=evan
      - --bitcoin-rpcpassword=thepass
      - --network=regtest
      - --log-level=debug
      - --alias=sphinx-cln1
      - --grpc-port=10012
      - --accept-htlc-tlv-types=133773310
    environment:
      - EXPOSE_TCP=true
      - GREENLIGHT_VERSION=v23.02.2-50-gd15200c
    ports:
      - "0.0.0.0:9738:9735"
      - 10012:10012
    links:
      - bitcoind.sphinx
    volumes:
      - ./cln/cln1:/root/.lightning
```
